---
# Common tasks (Nginx is EPEL package)
- name: Install required packages
  package:
    name: "{{ item }}"
  with_items:
    - ntp-4.2.6p5-25.el7.centos.2.x86_64
    - nginx-1.12.2-1.el7.x86_64

- name: Configure NTP Daemon
  template:
    src: ntp/ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart time daemon

- name: Configure Nginx with SSL enabled via slef
  template:
    src: templates/nginx/nginx.conf.j2
    dest: "{{ nginx_conf_file }}"
  notify:
    - restart nginx

- name: create directories to store our self generated TLS/SSL Certs
  file:
    path: "{{ certificate_directory }}"
    state: directory

- name: copy TLS key
  copy:
    src: "files/{{ tls_key_file }}"
    dest: "{{ certificate_directory }}"
    owner: root
    mode: 0600
  notify:
    - restart nginx

- name: copy TLS cert
  copy:
    src: "files/{{ tls_cert_file }}"
    dest: "{{ certificate_directory }}"
  notify:
    - restart nginx

# - name: copy nginx config file
#   template:
#     src: templates/nginx.conf.j2
#     dest: "{{ ngin_conf_file }}"

# - name: enable configuration via symlink
#   file: dest=/etc/nginx/sites-enabled/default src={{ conf_file }} state=link
#   notify: restart nginx

- name: copy test file index.html to Nginx
  template:
    src: templates/nginx/index.html.j2
    dest: "{{ nginx_html }}/index.html"
    mode: 0644
  notify:
    - restart nginx
